/************************************************************************
 * @description Constants usadas nas macros VBA e no objeto 'Excel.Application'
 * @author Pedro Henrique C. Xavier
 * @date 2024-03-19
 * @version 2.1-alpha.8
 ***********************************************************************/

#Requires AutoHotkey v2.0

const := {
    xl3DBar: -4099,
    xl3DEffects1: 13,
    xl3DEffects2: 14,
    xl3DSurface: -4103,
    xlAbove: 0,
    xlAccounting1: 4,
    xlAccounting2: 5,
    xlAccounting3: 6,
    xlAccounting4: 17,
    xlAdd: 2,
    xlAll: -4104,
    xlAllExceptBorders: 7,
    xlAutomatic: -4105,
    xlBar: 2,
    xlBelow: 1,
    xlBidi: -5000,
    xlBidiCalendar: 3,
    xlBoth: 1,
    xlBottom: -4107,
    xlCascade: 7,
    xlCenter: -4108,
    xlCenterAcrossSelection: 7,
    xlChart4: 2,
    xlChartSeries: 17,
    xlChartShort: 6,
    xlChartTitles: 18,
    xlChecker: 9,
    xlCircle: 8,
    xlClassic1: 1,
    xlClassic2: 2,
    xlClassic3: 3,
    xlClosed: 3,
    xlColor1: 7,
    xlColor2: 8,
    xlColor3: 9,
    xlColumn: 3,
    xlCombination: -4111,
    xlComplete: 4,
    xlConstants: 2,
    xlContents: 2,
    xlContext: -5002,
    xlCorner: 2,
    xlCrissCross: 16,
    xlCross: 4,
    xlCustom: -4114,
    xlDebugCodePane: 13,
    xlDefaultAutoFormat: -1,
    xlDesktop: 9,
    xlDiamond: 2,
    xlDirect: 1,
    xlDistributed: -4117,
    xlDivide: 5,
    xlDoubleAccounting: 5,
    xlDoubleClosed: 5,
    xlDoubleOpen: 4,
    xlDoubleQuote: 1,
    xlDrawingObject: 14,
    xlEntireChart: 20,
    xlExcelMenus: 1,
    xlExtended: 3,
    xlFill: 5,
    xlFirst: 0,
    xlFixedValue: 1,
    xlFloating: 5,
    xlFormats: -4122,
    xlFormula: 5,
    xlFullScript: 1,
    xlGeneral: 1,
    xlGray16: 17,
    xlGray25: -4124,
    xlGray50: -4125,
    xlGray75: -4126,
    xlGray8: 18,
    xlGregorian: 2,
    xlGrid: 15,
    xlGridline: 22,
    xlHigh: -4127,
    xlHindiNumerals: 3,
    xlIcons: 1,
    xlImmediatePane: 12,
    xlInside: 2,
    xlInteger: 2,
    xlJustify: -4130,
    xlLast: 1,
    xlLastCell: 11,
    xlLatin: -5001,
    xlLeft: -4131,
    xlLeftToRight: 2,
    xlLightDown: 13,
    xlLightHorizontal: 11,
    xlLightUp: 14,
    xlLightVertical: 12,
    xlList1: 10,
    xlList2: 11,
    xlList3: 12,
    xlLocalFormat1: 15,
    xlLocalFormat2: 16,
    xlLogicalCursor: 1,
    xlLong: 3,
    xlLotusHelp: 2,
    xlLow: -4134,
    xlLTR: -5003,
    xlMacrosheetCell: 7,
    xlManual: -4135,
    xlMaximum: 2,
    xlMinimum: 4,
    xlMinusValues: 3,
    xlMixed: 2,
    xlMixedAuthorizedScript: 4,
    xlMixedScript: 3,
    xlModule: -4141,
    xlMultiply: 4,
    xlNarrow: 1,
    xlNextToAxis: 4,
    xlNoDocuments: 3,
    xlNone: -4142,
    xlNotes: -4144,
    xlOff: -4146,
    xlOn: 1,
    xlOpaque: 3,
    xlOpen: 2,
    xlOutside: 3,
    xlPartial: 3,
    xlPartialScript: 2,
    xlPercent: 2,
    xlPlus: 9,
    xlPlusValues: 2,
    xlReference: 4,
    xlRight: -4152,
    xlRTL: -5004,
    xlScale: 3,
    xlSemiautomatic: 2,
    xlSemiGray75: 10,
    xlShort: 1,
    xlShowLabel: 4,
    xlShowLabelAndPercent: 5,
    xlShowPercent: 3,
    xlShowValue: 2,
    xlSimple: -4154,
    xlSingle: 2,
    xlSingleAccounting: 4,
    xlSingleQuote: 2,
    xlSolid: 1,
    xlSquare: 1,
    xlStar: 5,
    xlStError: 4,
    xlStrict: 2,
    xlSubtract: 3,
    xlSystem: 1,
    xlTextBox: 16,
    xlTiled: 1,
    xlTitleBar: 8,
    xlToolbar: 1,
    xlToolbarButton: 2,
    xlTop: -4160,
    xlTopToBottom: 1,
    xlTransparent: 2,
    xlTriangle: 3,
    xlVeryHidden: 2,
    xlVisible: 12,
    xlVisualCursor: 2,
    xlWatchPane: 11,
    xlWide: 3,
    xlWorkbookTab: 6,
    xlWorksheet4: 1,
    xlWorksheetCell: 3,
    xlWorksheetShort: 5,
    
    ; Enumeração XlBordersIndex
    xlDiagonalDown: 5,      ; Borda em execução do canto superior esquerdo para o canto inferior direito de cada célula no intervalo.
    xlDiagonalUp: 6,        ; Borda em execução do canto inferior esquerdo para o canto superior direito de cada célula no intervalo.
    xlEdgeBottom: 9,        ; Borda na parte inferior do intervalo.
    xlEdgeLeft: 7,          ; Borda na borda esquerda do intervalo.
    xlEdgeRight: 10,        ; Borda na borda direita do intervalo.
    xlEdgeTop: 8,           ; Borda na parte superior do intervalo.
    xlInsideHorizontal: 12, ; Bordas horizontais de todas as células do intervalo exceto a parte externa do intervalo.
    xlInsideVertical: 11,   ; Bordas verticais de todas as células do intervalo exceto a parte externa do intervalo.
}